Update cmake-windows.yaml

diff --git a/.github/workflows/cmake-windows.yaml b/.github/workflows/cmake-windows.yaml
--- a/.github/workflows/cmake-windows.yaml
+++ b/.github/workflows/cmake-windows.yaml
@@ -35,6 +35,11 @@ jobs:
       - name: Build project
         run: cmake --build build --config ${{ env.BUILD_TYPE }}
 
+      - name: Verify executables existence
+        run: |
+          if (!(Test-Path -Path "build/Release/TestApp.exe")) { Write-Error "TestApp.exe not found"; exit 1 }
+          if (!(Test-Path -Path "build/Release/QmlTests.exe")) { Write-Error "QmlTests.exe not found"; exit 1 }
+
       - name: Deploy Qt DLLs for executables
         run: |
           & "D:/a/test-windows/Qt/5.15.2/msvc2019_64/bin/windeployqt.exe" --qmldir=qml build/Release/TestApp.exe
